build:
	docker build -t birkoffh/fundassigment-api .

run:
	docker run -i -t -p 8080:80 -v /Users/hector/workspace/funda_api_stats/api_stats:/var/www/funda_analytics_api birkoffh/fundassigment-api sh /bootstrap.sh