Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowRunningDataCollector
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: LambdaLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  LambdaDataCollector:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: ApiDataCollector
      Handler:
        Ref: LambdaHandler
      Role:
        Fn::GetAtt:
          - "LambdaExecutionRole"
          - "Arn"
      Environment:
        Variables:
          DB_HOSTNAME:
            Ref: DbHOSTNAME
          DB_USERNAME:
            Ref: DbUSERNAME
          DB_PASSWORD:
            Ref: DbPASSWORD
          DB_NAME:
            Ref: DbNAME
          DB_TABLE:
            Ref: DbTABLE
          API_KEY:
            Ref: ApiKEY
      Code:
        S3Bucket:
          Ref: LambdaFunctionS3Bucket
        S3Key:
          Ref: LambdaFunctionS3Key
      Runtime:
        Ref: LambdaRuntime
      Timeout:
        Ref: LambdaTimeout


  LambdaExecutionRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: "rate(1 day)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "LambdaDataCollector"
              - "Arn"
          Id: "TargetFunctionV1"

  PermissionForEventsToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        Fn::GetAtt:
          - "LambdaDataCollector"
          - "Arn"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "LambdaExecutionRule"
          - "Arn"